# Generated by Django 3.2.4 on 2022-03-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('inactive', models.BooleanField(default=False, verbose_name='Inactive')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Input_item',
                'verbose_name_plural': 'Input_items',
                'ordering': ['date'],
            },
        ),
    ]
