# Generated by Django 3.2.4 on 2022-03-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0002_alter_input_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input_item',
            old_name='descricao',
            new_name='Description',
        ),
    ]
