# Generated by Django 3.2.4 on 2021-06-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_auto_20210605_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.image', verbose_name='Image')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'WordImage',
                'verbose_name_plural': 'WordsImages',
            },
        ),
    ]
