# Generated by Django 3.2.4 on 2021-06-24 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_imageword'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.language', verbose_name='Language'),
        ),
        migrations.AlterUniqueTogether(
            name='imageword',
            unique_together={('word', 'image')},
        ),
    ]
