# Generated by Django 3.2.4 on 2021-07-29 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '0007_imageword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='article',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='word',
            name='sentence',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sentence'),
        ),
        migrations.AlterField(
            model_name='imageword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='imageword',
            unique_together={('user', 'word', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('user', 'word', 'language')},
        ),
    ]
