# Generated by Django 3.2.4 on 2021-08-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_auto_20210729_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AddField(
            model_name='language',
            name='nick',
            field=models.SlugField(blank=True, max_length=5, null=True, unique=True, verbose_name='nickname'),
        ),
    ]
